import type { FicResult } from '@/lib/schema/types';

export const MOCK_RESULTS: FicResult[] = [
  {
    id: 'ao3-1',
    platform: 'ao3',
    title: 'All the Young Dudes',
    author: 'MsKingBean89',
    url: 'https://archiveofourown.org/works/10057010',
    authorUrl: 'https://archiveofourown.org/users/MsKingBean89',
    rating: 'T',
    wordCount: 526969,
    chapters: '188/188',
    status: 'complete',
    tags: ['Marauders Era', 'Found Family', 'Coming of Age', 'Slow Burn', 'Canon Compliant'],
    summary: 'A coming-of-age story following Remus Lupin and his friends through their years at Hogwarts, dealing with werewolves, war, and love.',
    stats: { kudos: 89241, hits: 4200000, bookmarks: 18000 },
    matchScore: 94,
    updatedAt: '2018-11-10T00:00:00Z',
  },
  {
    id: 'ao3-2',
    platform: 'ao3',
    title: 'Drarry: In the Days That Remain',
    author: 'lol_phan_af',
    url: 'https://archiveofourown.org/works/15780021',
    authorUrl: 'https://archiveofourown.org/users/lol_phan_af',
    rating: 'M',
    wordCount: 103200,
    chapters: '25/25',
    status: 'complete',
    tags: ['Draco Malfoy/Harry Potter', 'Enemies to Lovers', 'Post-War', 'Slow Burn', 'Angst with Happy Ending'],
    summary: 'Years after the war, Harry and Draco are forced to work together on a Ministry assignment neither of them wanted.',
    stats: { kudos: 22300, hits: 890000, bookmarks: 4100 },
    matchScore: 89,
    updatedAt: '2019-04-22T00:00:00Z',
  },
  {
    id: 'ffn-1',
    platform: 'ffn',
    title: "Harry Potter and the Methods of Rationality",
    author: 'Less Wrong',
    url: 'https://www.fanfiction.net/s/5782108/1/',
    authorUrl: 'https://www.fanfiction.net/u/2269863/',
    rating: 'T',
    wordCount: 661619,
    chapters: '122/122',
    status: 'complete',
    tags: ['Alternate Universe', 'Rationalist', 'Humor', 'Dark', 'Complete'],
    summary: "Petunia married a biochemist, and Harry grew up reading science and science fiction. Now Hogwarts meets scientific rationalism.",
    stats: { favs: 42100, follows: 18300, reviews: 84000 },
    matchScore: 82,
    updatedAt: '2015-03-14T00:00:00Z',
  },
  {
    id: 'ao3-3',
    platform: 'ao3',
    title: "A Pureblood's Guide to Halfblood Customs",
    author: 'CelestialMercury',
    url: 'https://archiveofourown.org/works/23456789',
    authorUrl: 'https://archiveofourown.org/users/CelestialMercury',
    rating: 'T',
    wordCount: 78500,
    chapters: '18/18',
    status: 'complete',
    tags: ['Draco Malfoy', 'Hermione Granger', 'Culture Clash', 'Slow Burn', 'Muggle Culture'],
    summary: "Draco Malfoy is determined to understand Muggle culture after the war. Hermione Granger is reluctantly his guide.",
    stats: { kudos: 14200, hits: 420000, bookmarks: 2800 },
    matchScore: 76,
    updatedAt: '2021-07-03T00:00:00Z',
  },
  {
    id: 'ffn-2',
    platform: 'ffn',
    title: 'Underneath the Mistletoe',
    author: 'hollowstar',
    url: 'https://www.fanfiction.net/s/13200405/1/',
    authorUrl: 'https://www.fanfiction.net/u/9134521/',
    rating: 'T',
    wordCount: 52300,
    chapters: '12/12',
    status: 'complete',
    tags: ['Fluff', 'Holiday', 'Ron/Hermione', 'Post-War', 'Canon Compliant'],
    summary: 'Ron and Hermione navigate their first Christmas together as a couple, dealing with family expectations and their own awkward hearts.',
    stats: { favs: 3400, follows: 1200, reviews: 6700 },
    matchScore: 71,
    updatedAt: '2020-12-25T00:00:00Z',
  },
  {
    id: 'ao3-4',
    platform: 'ao3',
    title: 'Foundations!verse',
    author: 'SilentAuror',
    url: 'https://archiveofourown.org/series/123456',
    authorUrl: 'https://archiveofourown.org/users/SilentAuror',
    rating: 'E',
    wordCount: 245000,
    chapters: '62/62',
    status: 'complete',
    tags: ['Post-Hogwarts', 'Auror Partners', 'Slow Burn', 'Drarry', 'Long Fic'],
    summary: 'Harry and Draco work as Auror partners and slowly, reluctantly fall in love over the course of a very long year.',
    stats: { kudos: 31200, hits: 1100000, bookmarks: 7400 },
    matchScore: 88,
    updatedAt: '2017-09-14T00:00:00Z',
  },
  {
    id: 'ffn-3',
    platform: 'ffn',
    title: 'The Depths We Dive',
    author: 'RiverRun22',
    url: 'https://www.fanfiction.net/s/14100220/1/',
    authorUrl: 'https://www.fanfiction.net/u/11234567/',
    rating: 'M',
    wordCount: 115000,
    chapters: '28/28',
    status: 'complete',
    tags: ['Dark', 'Fix-It', 'Angst', 'Redemption Arc', 'Post-War'],
    summary: 'In a world where the Battle of Hogwarts went differently, survivors must rebuild—including people you never expected to survive.',
    stats: { favs: 8900, follows: 3400, reviews: 12000 },
    matchScore: 68,
    updatedAt: '2022-11-01T00:00:00Z',
  },
  {
    id: 'ao3-5',
    platform: 'ao3',
    title: 'Inevitable',
    author: 'astolat',
    url: 'https://archiveofourown.org/works/87654321',
    authorUrl: 'https://archiveofourown.org/users/astolat',
    rating: 'E',
    wordCount: 43000,
    chapters: '1/1',
    status: 'complete',
    tags: ['Drarry', 'Humor', 'Accidental Bond', 'Pining', 'Oblivious Harry'],
    summary: "There's a magical bond. Harry is oblivious. Draco is suffering. Draco is always suffering.",
    stats: { kudos: 27800, hits: 780000, bookmarks: 5600 },
    matchScore: 85,
    updatedAt: '2016-06-20T00:00:00Z',
  },
  {
    id: 'ao3-6',
    platform: 'ao3',
    title: 'The Boy Who Lived (And Lived, And Lived)',
    author: 'timeloop_writer',
    url: 'https://archiveofourown.org/works/34567890',
    authorUrl: 'https://archiveofourown.org/users/timeloop_writer',
    rating: 'T',
    wordCount: 189000,
    chapters: '45/45',
    status: 'complete',
    tags: ['Time Loop', 'Harry-centric', 'Dark Comedy', 'Fix-It', 'Gen'],
    summary: 'Harry Potter dies and wakes up at the beginning again. And again. And again. He is very tired.',
    stats: { kudos: 19400, hits: 650000, bookmarks: 4200 },
    matchScore: 79,
    updatedAt: '2023-02-14T00:00:00Z',
  },
  {
    id: 'ffn-4',
    platform: 'ffn',
    title: 'Serpent in Gryffindor',
    author: 'DarkQuill99',
    url: 'https://www.fanfiction.net/s/11000333/1/',
    authorUrl: 'https://www.fanfiction.net/u/6789012/',
    rating: 'T',
    wordCount: 264000,
    chapters: '67/67',
    status: 'complete',
    tags: ['Dark Harry', 'Slytherin AU', 'Political Intrigue', 'Morally Gray', 'Complete'],
    summary: 'What if the Sorting Hat had listened to Harry? A cunning, ambitious Harry navigates Slytherin politics and a very different war.',
    stats: { favs: 15600, follows: 7800, reviews: 24000 },
    matchScore: 74,
    updatedAt: '2019-08-30T00:00:00Z',
  },
];
